# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

"""Core logic for ``opcli pytest expand`` and ``opcli pytest run``.

Reads ``artifacts.build.yaml`` (schema v1) and assembles the flags that
tox/pytest need to locate built charms and their OCI-image resources.

Convention (matching operator-workflows):
    --charm-file=<path>             for each locally built charm
    --<rock-name>-image=<path>      for each rock (directly, regardless of charm links)
    --<resource-name>=<path>        for OCI-image resources not backed by a rock

Rock image flags are generated by iterating over ``rocks`` directly, so no
explicit ``rock:`` annotation in ``artifacts.yaml`` is required.  The
``rock:`` field is still used for publishing (knowing which rock backs which
charm resource), but it is not needed for test flag generation.

The ``KEY=VALUE`` form is required because some conftest.py files register
``--charm-file`` with ``nargs="+"``, which makes argparse greedy.  With the
space-separated form, subsequent ``--charm-file`` tokens would be consumed as
values of the first flag instead of starting a new flag.

When the generated file contains multi-arch builds, flags are filtered to the
current machine's architecture.  If no build matches the current arch, all
available builds are used (graceful degradation for single-arch repos).
"""

import logging
from pathlib import Path
from typing import overload

from opcli.core.constants import ARTIFACTS_BUILD_YAML
from opcli.core.env import current_arch, is_ci
from opcli.core.exceptions import ConfigurationError
from opcli.core.secrets import load_secrets_env
from opcli.core.subprocess import run_command
from opcli.core.template import render_arguments_template, render_environment_template
from opcli.core.yaml_io import load_artifacts_build
from opcli.models.artifacts_build import (
    CharmOutput,
    RockOutput,
    SnapOutput,
)

logger = logging.getLogger(__name__)


def pytest_run(  # noqa: PLR0913
    root: Path,
    *,
    tox_env: str = "integration",
    extra_args: list[str] | None = None,
    ci: bool | None = None,
    suite_config: dict[str, str | None] | None = None,
    cwd: Path | None = None,
) -> None:
    """Assemble the tox command and execute it interactively.

    In local mode, secrets from ``.secrets.env`` (if present) are loaded and
    passed as environment variables to the tox subprocess.  In CI mode the
    variables are expected to already be in the environment.

    Artifact paths are communicated to the test framework via:
    - Default (no template): ``--charm-file`` and rock image flags (pfe style).
    - ``pytest-arguments-template``: Jinja2 template rendered into CLI args.
    - ``pytest-environment-template``: Jinja2 template rendered into env vars.

    When *cwd* is provided, tox is executed from that directory instead of
    *root*.  This supports multi-charm monorepos where each sub-charm has
    its own ``tox.toml``.

    Raises:
        ConfigurationError: If ``artifacts.build.yaml`` is missing.
        SubprocessError: If tox exits non-zero.
    """
    cfg = suite_config or {}
    cmd = assemble_tox_argv(
        root, tox_env=tox_env, extra_args=extra_args, suite_config=cfg, cwd=cwd
    )

    is_ci_env = ci if ci is not None else is_ci()
    env: dict[str, str] = {}
    if not is_ci_env:
        loaded = load_secrets_env(root)
        if loaded:
            env.update(loaded)

    # Render environment template if present
    env_template = cfg.get("pytest-environment-template")
    if isinstance(env_template, str):
        rendered_env = render_environment_template(root, env_template)
        env.update(rendered_env)

    execution_dir = str(cwd) if cwd else str(root)
    run_command(cmd, cwd=execution_dir, interactive=True, env=env or None)


def assemble_tox_argv(
    root: Path,
    *,
    tox_env: str = "integration",
    extra_args: list[str] | None = None,
    suite_config: dict[str, str | None] | None = None,
    cwd: Path | None = None,
) -> list[str]:
    """Build the full tox argv for running integration tests.

    Returns a list of tokens suitable for shell execution or display via
    ``shlex.join()``.  The ``--`` separator is included only when there are
    pytest flags or forwarded extra args to pass.

    When *cwd* differs from *root*, artifact paths are made absolute so
    they resolve correctly from the execution directory.

    If ``pytest-arguments-template`` is present in *suite_config*, the
    template is rendered and its output tokens replace the default flags.
    Otherwise the default pfe-style flags are generated.

    Raises:
        ConfigurationError: If required YAML files are missing.
    """
    cfg = suite_config or {}
    args_template = cfg.get("pytest-arguments-template")

    if isinstance(args_template, str):
        pytest_args = render_arguments_template(root, args_template) + (extra_args or [])
    else:
        # Default: pfe-style flag generation
        assembled = assemble_pytest_args(root, cwd=cwd)
        pytest_args = assembled + (extra_args or [])

    cmd: list[str] = ["tox", "-e", tox_env]
    if pytest_args:
        cmd += ["--", *pytest_args]
    return cmd


def assemble_pytest_args(  # noqa: C901
    root: Path,
    *,
    cwd: Path | None = None,
) -> list[str]:
    """Build the list of pytest flags from the generated artifacts.

    When *cwd* differs from *root*, charm/rock paths are made absolute so
    they resolve correctly from the execution directory.

    Returns:
        A list of CLI flags like
        ``["--charm-file=path.charm", "--img=path.rock"]``.

    Raises:
        ConfigurationError: If ``artifacts.build.yaml`` is missing.
    """
    gen_path = root / ARTIFACTS_BUILD_YAML
    if not gen_path.exists():
        msg = f"{ARTIFACTS_BUILD_YAML} not found. Run 'opcli artifacts build' first."
        raise ConfigurationError(msg)

    generated = load_artifacts_build(gen_path)
    arch = current_arch()

    # When cwd differs from root, resolve relative paths against root
    needs_absolute = cwd is not None and cwd.resolve() != root.resolve()

    def _resolve_path(p: str) -> str:
        if not needs_absolute:
            return p
        path = Path(p)
        if path.is_absolute():
            return p
        return str((root / path).resolve())

    args: list[str] = []

    # Rock image flags — one per rock, matching operator-workflows convention.
    # This runs unconditionally so no rock: annotation is needed on charm resources.
    rock_flag_names: set[str] = set()
    for rock in generated.rocks:
        rock_builds = _select_arch_builds(rock.builds, arch, rock.name)
        for rock_build in rock_builds:
            value = rock_build.image or rock_build.file
            if value:
                flag_name = f"{rock.name}-image"
                rock_flag_names.add(flag_name)
                # Only resolve file paths, not image references
                resolved = _resolve_path(value) if rock_build.file else value
                args.append(f"--{flag_name}={resolved}")

    for charm in generated.charms:
        charm_builds = _select_arch_builds(charm.builds, arch, charm.name)
        for charm_build in charm_builds:
            if charm_build.path:
                args.append(f"--charm-file={_resolve_path(charm_build.path)}")
            elif charm_build.artifact:
                logger.warning(
                    "Skipping --charm-file for charm '%s' (%s): output is a CI "
                    "artifact (%s). Run 'opcli artifacts build' locally to get "
                    "a local file.",
                    charm.name,
                    charm_build.arch,
                    charm_build.artifact,
                )

        # Resources backed by a rock are already covered by the rock
        # iteration above. Resources without a rock link have no output info.
        for res_name, res in (charm.resources or {}).items():
            if res.rock:
                continue
            if res_name in rock_flag_names:
                logger.warning(
                    "Skipping resource '%s' for charm '%s': flag name '--%s' "
                    "already emitted by a rock with the same name.",
                    res_name,
                    charm.name,
                    res_name,
                )
                continue

    return args


# ---------------------------------------------------------------------------
#  Private helpers
# ---------------------------------------------------------------------------


@overload
def _select_arch_builds(
    builds: list[RockOutput], arch: str, artifact_name: str
) -> list[RockOutput]: ...


@overload
def _select_arch_builds(
    builds: list[CharmOutput], arch: str, artifact_name: str
) -> list[CharmOutput]: ...


@overload
def _select_arch_builds(
    builds: list[SnapOutput], arch: str, artifact_name: str
) -> list[SnapOutput]: ...


def _select_arch_builds(
    builds: list[RockOutput] | list[CharmOutput] | list[SnapOutput],
    arch: str,
    artifact_name: str,
) -> list[RockOutput] | list[CharmOutput] | list[SnapOutput]:
    """Return the subset of *builds* matching *arch*, or all if none match.

    When an exact arch match is found, only those builds are returned.
    When no build matches the current arch (e.g. running arm64 tests against
    an amd64-only artifact set), all builds are returned with a warning so
    that single-arch repos continue to work.
    """
    matching = [b for b in builds if b.arch == arch]
    if matching:
        return matching  # type: ignore[return-value]
    if builds:
        logger.warning(
            "No build for '%s' matches arch '%s'; using all available builds: %s",
            artifact_name,
            arch,
            [b.arch for b in builds],
        )
    return builds
