# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

"""Core logic for ``opcli pytest expand`` and ``opcli pytest run``.

Assembles the tox command for running integration tests.  Artifacts are
injected into test functions via the pytest-opcli plugin fixtures
(``charm_path``, ``rock_images``, etc.); no CLI flags are generated by
default.

Custom flags or environment variables can be passed to pytest via
``pytest-arguments-template`` and ``pytest-environment-template`` keys
in the ``integration-suites`` entry in ``spread.yaml``.
"""

import logging
from pathlib import Path

from opcli.core.env import is_ci
from opcli.core.secrets import load_secrets_env
from opcli.core.subprocess import run_command
from opcli.core.template import render_arguments_template, render_environment_template

logger = logging.getLogger(__name__)


def pytest_run(  # noqa: PLR0913
    root: Path,
    *,
    tox_env: str = "integration",
    extra_args: list[str] | None = None,
    ci: bool | None = None,
    suite_config: dict[str, str | None] | None = None,
    cwd: Path | None = None,
    module_path: str | None = None,
) -> None:
    """Assemble the tox command and execute it interactively.

    In local mode, secrets from ``.secrets.env`` (if present) are loaded and
    passed as environment variables to the tox subprocess.  In CI mode the
    variables are expected to already be in the environment.

    Artifact paths are communicated to the test framework via the pytest-opcli
    plugin fixtures (``charm_path``, ``rock_images``, etc.).  Custom pytest
    flags or environment variables can be added via ``pytest-arguments-template``
    or ``pytest-environment-template`` in the suite's ``integration-suites``
    entry.

    When *cwd* is provided, tox is executed from that directory instead of
    *root*.  This supports multi-charm monorepos where each sub-charm has
    its own ``tox.toml``.

    Raises:
        SubprocessError: If tox exits non-zero.
    """
    cfg = suite_config or {}
    cmd = assemble_tox_argv(
        root,
        tox_env=tox_env,
        extra_args=extra_args,
        suite_config=cfg,
        module_path=module_path,
    )

    is_ci_env = ci if ci is not None else is_ci()
    env: dict[str, str] = {}
    if not is_ci_env:
        loaded = load_secrets_env(root)
        if loaded:
            env.update(loaded)

    # Render environment template if present
    env_template = cfg.get("pytest-environment-template")
    if isinstance(env_template, str):
        rendered_env = render_environment_template(root, env_template)
        env.update(rendered_env)

    execution_dir = str(cwd) if cwd else str(root)
    run_command(cmd, cwd=execution_dir, interactive=True, env=env or None)


def assemble_tox_argv(
    root: Path,
    *,
    tox_env: str = "integration",
    extra_args: list[str] | None = None,
    suite_config: dict[str, str | None] | None = None,
    module_path: str | None = None,
) -> list[str]:
    """Build the full tox argv for running integration tests.

    Returns a list of tokens suitable for shell execution or display via
    ``shlex.join()``.  The ``--`` separator is included only when there are
    pytest flags or forwarded extra args to pass.

    If *module_path* is provided, it is prepended to the pytest posargs so
    that pytest discovers the test file's ``conftest.py`` (and its
    ``pytest_addoption`` hooks) before parsing the remaining arguments.

    If ``pytest-arguments-template`` is present in *suite_config*, the
    template is rendered and its output tokens are passed after ``--``.
    Otherwise only *extra_args* (if any) are forwarded — artifacts are
    injected into tests via the pytest-opcli plugin fixtures.

    Raises:
        ConfigurationError: If a template is set but ``artifacts.build.yaml``
        is missing.
    """
    cfg = suite_config or {}
    args_template = cfg.get("pytest-arguments-template")

    pytest_args: list[str] = []
    if module_path:
        pytest_args.append(module_path)
    if isinstance(args_template, str):
        pytest_args += render_arguments_template(root, args_template) + (extra_args or [])
    else:
        pytest_args += extra_args or []

    cmd: list[str] = ["tox", "-e", tox_env]
    if pytest_args:
        cmd += ["--", *pytest_args]
    return cmd
